services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cinema
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis-cinema
    hostname: redis-cinema
    restart: always
    ports:
      - "6379:6379"
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    networks:
      - default

  backend-service:
    container_name: backend-service
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MYSQL_HOST=mysql-cinema
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis-cinema
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - JWT_AC=fPEZIjt0xHDMP/TlLjuXBuXCyN9HuB498CEQXZ39oiQ=
      - JWT_RF=TN13ztj3wnw/DC9qiDz+pU/DaxztO6ZF1x33kqbvdhM=
      - CLOUDINARY_KEY=153747759143969
      - CLOUDINARY_SECRET=yNwJ5U70IQ9uGc1UM-rjXp869tk
      - CLOUDINARY_NAME=djtohfqmr
      - ZALOPAY_KEY1=sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn
      - ZALOPAY_KEY2=trMrHtvjo6myautxDUiAcYsVtaeQ8nhf
      - ZALOPAY_ID=2554
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - default

networks:
  default:
    name: backend-network
    driver: bridge

volumes:
  mysql_data:
